### ISSUE TITLE
USB-C Mods design

### ISSUE THREAD

**Issue by B0jack91** [rorosaurus/gba-sp-usb-c#4]
Hello @rorosaurus,

I was wondering if somehow it was possible to get the files for the pcb boards you designed for gba sp and nds lite. Im starting to learn more about modding and soldering these consoles and found your github and really interesting content you wrote. But noticed you stopped selling those USB-C ports (my assumption) so I was wondering if it was possible for you to consider publishing the PCB designs so others could keep working on modding using your mod instead of makho one, as basically yours seem to be an improved version of his.

Apologies if I bother you, not my intention, I am just trying to educate myself and was considering either buying your mod usb-c port, or if not available (as it looks) print it over sites as OSH Park.

Thank you so much for your time.
Best regards,

**Comment by ABaumher** [comment]
may be somewhat late here but those files are shared in this repo. I'm in the process of doing this myself, and need this version as i indend to do this alongside a 3.5mm audio mod, which makes any other options available less ideal. That said, i have zero experience in generating PCBs, so take this with a grain of salt, i can't guarentee i will succeed, YMMV, etc.

It appears these were designed in easaeda, which is a tool for generating PCBs. The files were exported to a Gerber file, which is a zip folder containing various files needed to manufacture the PCB. PCB manufacturers can take this zip and generate a PCB for you. 
The Gerber zip for this repo is at https://github.com/rorosaurus/gba-sp-usb-c/blob/master/gerber/gerber-gba-sp-usb-c-pcb.zip
I was able to dowload the zip from above, then upload it at the manufacturing site [jlcpcb.com](https://jlcpcb.com/). I have heard good things about PCBWay as well, but their webpage is not as intuitive, and since i have less than zero experience in this, the simpler site won out ¯\\_(ツ)_/¯
Their minimum quantity is 5, and estimated cost for me is $2USD (plus shipping). 
From there, it also requires a transistor and the USB C port, which are listed in the gerber/ordering.md file. I've linked the two below for ease of access.
USB-C port used: https://www.aliexpress.com/item/32885941456.html 
5.1K resistors used: https://www.aliexpress.com/item/32864744837.html
I'm expecting that i'll need to solder all of that together myself; if i can find a youtube video demonstrating this process, i will link it.

**Comment by ABaumher** [comment]
Alternatively, the design available from Robot Retro, on https://handheldlegend.com/products/game-boy-advance-sp-usb-c-pcb-robot-retro is... eerily similar. Not sure that's in the spirit of the CC non-commercial license here, (the board layout is virtually identical, they just us different connection paths. Not a lawyer so i won't argue if this is legal, but it seems dubious), but it means that it probably works just as well as this design. A question on the site states it does support 5V testing, though they don't make personal guarentees like the statements here, so take that as you will. 

Edit: On principal, i would recommend using https://handheldlegend.com/products/usb-c-mod-for-game-boy-advance-sp instead. Same reseller, but their own in-house model. This version is at least their own design, not a blatant rip-off. (It puts a transistor on both sides of the usb-c port, instead of 2 off to the side on a little tab. it also uses both alignment pins as grounds instead of just one). It also has the benefit of aligning with the edge of the GBA SP motherboard, which may make installation easier. It also seems to leave the pins exposed i'd need for the 3.5mm audio jack mod. At this time, i've opted instead to go with this; if it does not work i will try building my own as noted above

**Comment by B0jack91** [comment]
Hey @ABaumher 
Thanks a lot, this is really helpful!
